master:
  image: redis:latest
  command: redis-server --port 16479
  ports:
    - "16479:16479"
slave:
  image: redis:latest
  command: redis-server --port 16579 --slaveof redis-master 16479
  links:
    - master:redis-master
  ports:
    - "16579:16579"
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave
  ports:
    - "26379:26379"