redis:
  image: redis:latest
  command: redis-server --port 16479 --appendonly yes
  restart: on-failure
  volumes:
    - "/var/www/redis/data:/data"
  ports:
    - "16479:16479"

sentinel:
  build: sentinel
  environment:
    - SENTINEL_MASTER_IP=ip
    - SENTINEL_MASTER_PORT=port
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - redis
  restart: on-failure 
  ports:
    - "26379:26379"